# -*- coding: utf-8 -*-
"""OPIM 5512 A02 Team Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-x7VCYozWyThF0aMHMgIiXfiSLVajqv4
"""

from sklearn.datasets import fetch_california_housing
from sklearn.neural_network import MLPRegressor
import pandas as pd
import matplotlib.pyplot as plt


# Load California Housing dataset
housing = fetch_california_housing(as_frame=True)

# Features + target as a single DataFrame
df = housing.frame

# Quick check
print(df.head())
print(df.shape)

# Split into feature and target variables
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

# Split into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Create MLPRegressor model with specified parameters
mlpRegress = MLPRegressor(
    hidden_layer_sizes=(100,50),
    random_state=42,
    max_iter=1000,
    early_stopping=True,
    validation_fraction=0.1,
    tol=0.0001
    )

# Fit the MLPRegressor model on X_train and y_train
mlpRegress.fit(X_train, y_train)

# Make predictions on the training data
y_train_pred = mlpRegress.predict(X_train)

# Add predictions as a new column in the training DataFrame
train_results = X_train.copy()
train_results['Actual'] = y_train
train_results['Predicted'] = y_train_pred

# Quick check of the first few rows
print(train_results.head())

# Plot actual vs predicted values
plt.figure(figsize=(8,6))
plt.scatter(y_train, y_train_pred, alpha=0.5, color='blue')
plt.plot([y_train.min(), y_train.max()], [y_train.min(), y_train.max()], 'r--', linewidth=2)
plt.xlabel('Actual Median House Value')
plt.ylabel('Predicted Median House Value')
plt.title('MLPRegressor: Actual vs Predicted on Training Data')
plt.show()