# -*- coding: utf-8 -*-
"""OPIM 5512 A02 Team Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-x7VCYozWyThF0aMHMgIiXfiSLVajqv4
"""

from sklearn.datasets import fetch_california_housing
import pandas as pd

# Load California Housing dataset
housing = fetch_california_housing(as_frame=True)

# Features + target as a single DataFrame
df = housing.frame

# Quick check
print(df.head())
print(df.shape)

# Split into feature and target variables
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

# Split into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)